### ISSUE TITLE
I hope the shooting path is not based on tiles, but on pixel points, forming a straight line.

### ISSUE THREAD

**Issue by jcy1001** [WhiteCloud0123/CDDA-Breeze#604]
### Is your feature request related to a problem? Please describe.

I hope the shooting path is not based on tiles, but on pixel points, forming a straight line.

### Solution you would like.

I hope the shooting path is not based on tiles, but on pixel points, forming a straight line.

**Comment by WhiteCloud0123** [comment]
请问你期望的是？

1 只是希望射击轨迹的画面表现看起来是基于像素的直线，其他方面的处理与原先保持一致。

2 不仅仅是射击轨迹的画面表现是基于像素的直线，其他方面的处理也能够做出一定程度的改变。

**Comment by jcy1001** [comment]
最低期望是射击轨迹的画面表现看起来是基于像素的直线，其他方面的处理与原先保持一致是可以的
