### ISSUE TITLE
安卓端每次按返回都会导致快捷键丢失

### ISSUE THREAD

**Issue by brezee1204** [WhiteCloud0123/CDDA-Breeze#736]
### 描述你遇到的bug

在安卓手机上使用全面屏手势返回呼出小键盘时，每次都会让快捷键丢失，特别不方便。
以前的版本没有这种情况。
辛苦作者看一下。

### 复现bug的步骤

![Screenshot_2024-07-18-15-53-10-226_WhiteCloud CDDA_Breeze](https://github.com/user-attachments/assets/bdef93d6-e937-4e82-86ab-cf058f0f2231)
![Screenshot_2024-07-18-15-53-15-361_WhiteCloud CDDA_Breeze](https://github.com/user-attachments/assets/75fedcd9-432f-4c53-bb59-bac6afdbd08d)
![Screenshot_2024-07-18-15-53-18-791_WhiteCloud CDDA_Breeze](https://github.com/user-attachments/assets/16f4c48d-6a88-4a23-bcbc-8aa47e4bd8f3)

### 游戏版本

8.6

**Comment by WhiteCloud0123** [comment]
这种情况无论是在原版还是breeze都是存在的。

返回键呼出键盘时，会自动隐藏快捷键，之后再按一次返回键即可以收起键盘，同时显示快捷键。

你突然注意到了这个问题的原因，可能是你使用了小键盘，但是没有使用返回键来关闭小件盘，而是使用了小键盘自带是收起按钮，这时虚拟按键是不显示的。

**Comment by WhiteCloud0123** [comment]
这应该是原版与breeze都存在的情况。

当你按返回键的时候，会自动的显示键盘，同时隐藏快捷键，之后再按一次返回，键盘消失，虚拟按键显示。

如果你使用了键盘自带的收起按钮，那么虚拟按键不会显示。你只能再次按下虚拟按键重复正常的流程。

这其实不算是个bug，改善体验那就是另一回事了。

**Comment by brezee1204** [comment]
https://github.com/user-attachments/assets/893224e0-f514-44c7-bf45-a31075f7b578



感谢作者回复。不过请看我的录屏。经过全面屏手势的返回操作，快捷键消失。

讯飞输入法如此，更换过其他输入法也一样。所以应该不是输入法问题

目前我自己的解决方法是按一下tab，可以重新唤出快捷键。如果有下一版本更新，不知道您能不能改善一下这个状况。

感谢作者的工作

**Comment by WhiteCloud0123** [comment]
对于手势操作，我在自己的手机上测试是没有问题。可能是手机系统相关的地方有些特别之处，每个厂商都有自己的一套定制，在一些细节方面更是有很多不同，这方面短期内没有办法提供什么帮助。

**Comment by WhiteCloud0123** [comment]
可以看下方的视频，在我的手机上进行测试，即使是手势操作也是正常的，虚拟按键正常隐藏/显示。
https://github.com/user-attachments/assets/68e82572-9e6f-4e05-858f-e2d9f2303d79

可能是手机系统相关的地方有些特别之处也可能是其他问题，每个厂商都有自己的一套定制，在一些细节方面更是有很多不同，这方面短期内没有办法提供什么帮助。

**Comment by brezee1204** [comment]
明白了，感谢回复。

可能是小米最近更新了系统。 Miui变成hyper os了。

现在也能玩，慢慢地就顺手了。

**Comment by WhiteCloud0123** [comment]
关于改善安卓“键盘弹出收回的流程”是有计划的，目前比较简单直接的办法是添加一个快捷键。当然也在看看其他的方式。
