### ISSUE TITLE
 安装某cbm无报错直接游戏闪退

### ISSUE THREAD

**Issue by HAPPYSCH** [WhiteCloud0123/CDDA-Breeze#737]
### 描述你遇到的bug

安装神经突触加速cbm成功的瞬间会卡死闪退 失败不会闪退

### 上传你的存档

[SAVE.zip](https://github.com/user-attachments/files/16374748/SAVE.zip)

### 复现bug的步骤

就是躺床上安装 其他啥额外行为也没有 

### 截图

![1](https://github.com/user-attachments/assets/5b13abd6-e107-4e47-9361-7dcc4307e44c)
![2](https://github.com/user-attachments/assets/40b53304-eadd-4e39-bfaf-4e2fdeea18f7)

### 游戏版本

CDDA-Breeze 2024-07-18-0555

**Comment by WhiteCloud0123** [comment]
由 #738 修复

**Comment by HAPPYSCH** [comment]
感谢修复
