### ISSUE TITLE
无限复制道具

### ISSUE THREAD

**Issue by yxxwj** [WhiteCloud0123/CDDA-Breeze#755]
### 描述你遇到的bug

幸存者军队的僵尸会掉落一件重型承重背心这个装备附带3个口袋是装了东西的如果是直接装备，每次重新进档就会在复制刷新一次口袋里面的东西，就是你捡到这个装备的时候里面装的什么就刷新什么

### 上传你的存档

[康科德-trimmed.tar.gz](https://github.com/user-attachments/files/16425170/-trimmed.tar.gz)

### 复现bug的步骤

杀死幸存者军队的怪物，找到重型承重背心，直接穿上，保存存档，退出重新进入就会刷新一份背心口袋里面的物品

### 截图

![Uploading Screenshot_20240730-074537_CDDA_Breeze.jpg…]()

### 游戏版本

微风最新版

**Comment by WhiteCloud0123** [comment]
可以重新上传一下你的存档吗？issue里附带的存档已损坏。幸存者军队的怪物是非自带mod的第三方mod中的怪物吗？请描述准确一些、

**Comment by yxxwj** [comment]
[康科德.zip](https://github.com/user-attachments/files/16425518/default.zip)
是非自带现代中的怪物，此问题的怪物来自幸存者军队的nod

**Comment by yxxwj** [comment]
[康科德-trimmed.tar.gz](https://github.com/user-attachments/files/16425576/-trimmed.tar.gz)
上面那个是直接压缩的存档，现在这个是最小化

**Comment by WhiteCloud0123** [comment]
我并不是很想受理使用了第三方mod的过程中游戏出现的bug，因为判断它到底是个原版问题还是第三方mod的问题是个有些费心的事情。breeze仅仅保证自带mod的兼容性。

**Comment by WhiteCloud0123** [comment]
我与他们的作者彼此之间也没有沟通的地方，之前添加的奥术、cata++都是有开源许可的。

**Comment by yxxwj** [comment]
以测试过，仅微风版本出现，应该是源码问题，而且有可能不止这个一个，可能原版也有这个问题只是没遇见最新版并不会出现这个问题

**Comment by WhiteCloud0123** [comment]
好

**Comment by yxxwj** [comment]
可能所有掉落装备带口袋里面装有物品的都会有这个问题，原版装备带口袋的装备比较少见所以没有发现，这个mod是固定出现这个带口袋的装备

**Comment by WhiteCloud0123** [comment]
可以上传一下幸存者军队mod吗？

**Comment by yxxwj** [comment]
[Uploading 幸存者.zip…]()

**Comment by yxxwj** [comment]
[Uploading 幸存者.zip…]()

**Comment by yxxwj** [comment]
[幸存者.zip](https://github.com/user-attachments/files/16426393/default.zip)

**Comment by WhiteCloud0123** [comment]
初步看上去，是游戏将包含内容物的物品，例如含有几个弹匣的三联火药袋作为一个口袋直接安装到了重型承重背心上。如果我们手动安装口袋，需要作为口袋的物品是空的。之后再去看看是mod的写法不太适合微风，还是其他问题。
![捕获](https://github.com/user-attachments/assets/b981f527-7d78-466e-ae00-3708a31535e2)

**Comment by yxxwj** [comment]
解决方法也很简单，卸下重新装上就不会在出现这个问题，因为在实验版试过没有出现这个问题，所有联系到可能是微风本体出现问题了所有反馈

**Comment by WhiteCloud0123** [comment]
这应该是实验版新增的特性。微风是根据0.G的。。。。。
