### ISSUE TITLE
重型电缆从电器出发连接自动断开，必须从蓄电池端链接

### ISSUE THREAD

**Issue by brezee1204** [WhiteCloud0123/CDDA-Breeze#783]
### 描述你遇到的bug

请看录屏，重型电缆不能在电器之间互相连接，显示“your 重型电缆  has come loose.只有蓄电池端才能连接

https://github.com/user-attachments/assets/f729005e-8a28-4323-b2e8-cef945815758

### 复现bug的步骤

9.3版本，使用重型电缆

### 是否使用了第三方mod

是

### 游戏版本

9.3

### 系统

安卓14

**Comment by WhiteCloud0123** [comment]
再次检查了游戏中本身的设置，这其实不是一个bug。本身重型电缆和跨接电缆就没有添加上vehicle_port这个目标，而如果你想首端连接上非蓄电类型的电器，你可以使用延长线。

**Comment by WhiteCloud0123** [comment]
新的release会被删除，然后这里真正要解决的是一个说明更加准确的问题。

**Comment by brezee1204** [comment]
> 新的release会被删除，然后这里真正要解决的是一个说明不清楚的问题。

好的，感谢您的辛苦工作

breeze是我玩过最好玩的dda

**Comment by WhiteCloud0123** [comment]
那个release指的是8月30号发布的版本，不是今天发布的版本。😬
