### ISSUE TITLE
安卓版本能不能恢复老版本的屏幕左上角tab按钮

### ISSUE THREAD

**Issue by brezee1204** [WhiteCloud0123/CDDA-Breeze#793]
### 描述你的请求

在下一个安卓版本中回复9.0版本（可能）的屏幕左上角tab按键

### 你设想中的解决方案

在进行近战攻击时，使用tab即可快速攻击。在移动设备上，屏幕左上角的tab非常好用。尤其是使用长矛时。但新版本取消了，自己也不能添加除了字符之外的命令。希望能添加一个选项，在现在“键盘”的右边添加一个tab按键

**Comment by WhiteCloud0123** [comment]
扩展按键会进行改进。但下一次更新就不知道什么时候了，最近有点忙了。😬

**Comment by WhiteCloud0123** [comment]
目前空余的英文字符有一个q，“放弃角色”也可以删除它的按键绑定，腾出一个“Q”。
可以为选择上面的字符为自动攻击添加上绑定，同时添加上对应的扩展按键。
