### ISSUE TITLE
汉化问题

### ISSUE THREAD

**Issue by yxxwj** [WhiteCloud0123/CDDA-Breeze#802]
### 描述你遇到的bug

我发现游戏未汉化项目无法正常读取mo文件，貌似是硬编码，例如给NPC培训技能表，NPC制作选项界面于选项，侧边栏人物受伤状态，治疗状态都无法正常读取mo文件，望汉化或修复

### 复现bug的步骤

省略

### 截图

![Uploading Screenshot_20240908-000611_MT_Manager.jpg…]()

### 是否使用了第三方mod

无

### 游戏版本

最新版

### 系统

安卓

**Comment by WhiteCloud0123** [comment]
将来有空的时候会去专门补充翻译，但最近有些忙了。😬

**Comment by WhiteCloud0123** [comment]
将来有空的时候会去专门补充翻译，但最近有些忙了。😬

**Comment by WhiteCloud0123** [comment]
如果你还发现了未翻译的部分，就继续补充在这个issue里吧。

**Comment by WhiteCloud0123** [comment]
另外，看你的描述，你可能遇到了放置位置不正确的问题。（我还没有去看是不是硬编码）。可以注意一下你的mod放置位置，如果你放置在内置的data/mods文件夹里的话，它是不会读取mo的。
需要手动在data同级目录下新建一个mods文件夹，然后把mo补充mod放进里面。假设你的mod中的mo路径也是正确的话。。。。。

**Comment by yxxwj** [comment]
好的，感谢，并不是mod，只是原版菜单或者功能汉化问题，在mo汉化了一次了并不是生效，不知道是我写法不对还是什么，有的生效有的不生效
