### ISSUE TITLE
NPC

### ISSUE THREAD

**Issue by yxxwj** [WhiteCloud0123/CDDA-Breeze#803]
### 描述你遇到的bug

NPC无法攻击各种路障后面的敌人例如沙袋路障等等，沙袋路障是可透视的，玩家可以站在后面进行射击，NPC并不会

### 复现bug的步骤

无

### 是否使用了第三方mod

无

### 游戏版本

最新

### 系统

安卓

**Comment by WhiteCloud0123** [comment]
我暂时想到的合理且简单一点的设计是：
- npc可以在紧挨着这些透视掩体时进行射击
- 在远离这些透视掩体的情况下，需要掩体地点的覆盖度<=60时（或者让玩家主动给npc设置阈值，或者覆盖度越高，npc决定射击的可能越低），npc才会决定进行射击。

**Comment by WhiteCloud0123** [comment]
它还牵扯到另一个需要解决、澄清的问题。
就是射出的子弹对于轨迹上的地形、家具是否会命中且造成破坏，我觉得有一些模糊、不太合理的地方。
