### ISSUE TITLE
物品享用范围

### ISSUE THREAD

**Issue by yxxwj** [WhiteCloud0123/CDDA-Breeze#818]
### 描述你遇到的bug

在以往的时候是13x13站在中心点位物品制作可以享受到最外围的物品，在中间建立实用货架还是家电，只要是不阻挡视野的都不会影响这个范围，今天发现突然影响了，图片中就是最下面的那排实用货架阻挡了最下面那排货架的享受，最好的结局方法是增加一个Y区域，工作区，在该范围内的都可以享用，类似于营地储物区，npc最好也可以享有，或者修复一下这个特性
![Screenshot_20240919-075409_CDDA_Breeze](https://github.com/user-attachments/assets/b38e8542-2d10-4c38-97a5-ab1b67ffdd52)
![Screenshot_20240919-075409_CDDA_Breeze](https://github.com/user-attachments/assets/c7e48da2-bcd7-43e6-b5c7-2abf620feec7)

### 复现bug的步骤

无

### 是否使用了第三方mod

无

### 游戏版本

最新版

### 系统

安卓

**Comment by yxxwj** [comment]
![Image_1722393102596](https://github.com/user-attachments/assets/06caf612-ffd1-43c9-af23-bcf469dedd95)
这是以前版本的构造，站在中心点可以享受到这一片范围的

**Comment by WhiteCloud0123** [comment]
看到了你的前后两次布局有变化，有可能是原来的一个隐蔽的bug。希望能再次确认一下有没有遗漏掉忽视掉一些其他因素。

需要上传一下最小化存档。👶

**Comment by WhiteCloud0123** [comment]
然后这个issue的版本一定要写清楚，不要写“最新版”👶

**Comment by WhiteCloud0123** [comment]
直到上传你的存档，或者我看到了其他玩家遇到这个问题，或者我正常游玩自己遇到了这个问题，此issue将被重新打开并进行修复。

**Comment by yxxwj** [comment]
> 看到了你的前后两次布局有变化,有可能是原来的一个隐蔽的bug .希望能再次确认一下有没有遗漏掉忽视掉一些其他因素。
> 
> 需要上传一下最小化存档。👶

好的，我重新开了一个纯净档，也是这个问题，会阻挡享用范围

**Comment by yxxwj** [comment]
[格洛弗斯维尔-trimmed.tar.gz](https://github.com/user-attachments/files/17052951/-trimmed.tar.gz)
这个是刚测试的依然是这个问题，我离原材料只有3格也依然无法在制作界面读取到

**Comment by yxxwj** [comment]
> 然后这个问题的版本一定要写清楚,不要写"最新版"👶

好的

**Comment by WhiteCloud0123** [comment]
可是我在那边放了几个碎木，然后刚好距离六格，然后按&进入制作，发现可以应用材料呀👶
![Screenshot_20240919_110109.jpg](https://github.com/user-attachments/assets/28d4143c-0fd9-4e9e-830c-891219d80632)

![Screenshot_20240919_110103.jpg](https://github.com/user-attachments/assets/059198ee-d2ea-4160-9645-123d5750fb16)

**Comment by WhiteCloud0123** [comment]
奥，但是却无法搜寻到原木材料却不行。

**Comment by WhiteCloud0123** [comment]
噗，不知道这到底算是个bug还是个特性。
有空会去看看，但还是希望这里能处理起来更加简单直观一点。😬

**Comment by WhiteCloud0123** [comment]
啊，这其实是个特性。
首先并不是在半径6格可视范围内的都可以，它还要考虑是不是在半径6格内到底是不是可到达的。

你之前的存档应该是没注意到一些细枝末节。上面截图测试的时候，是我的随身库存里有多于的碎木才有的结果。

**Comment by WhiteCloud0123** [comment]
![测试-01](https://github.com/user-attachments/assets/950c67d7-8eb2-47c8-a627-eacd35bed5e3)
![测试-02](https://github.com/user-attachments/assets/01af3036-6e10-4aad-96f2-ed40f8d9605d)

**Comment by WhiteCloud0123** [comment]
目前的话，尊重原版的设计我觉得问题不大，需要做的是添加一些说明，让玩家知道。游戏中像这样的黑箱还有很多。

**Comment by WhiteCloud0123** [comment]
![dda实验-测试](https://github.com/user-attachments/assets/2a192688-bb2c-4af9-8a26-914c3bdff73f)

在dda的实验版上测试了，一样的结果。

**Comment by yxxwj** [comment]
> ![dda实验-测试](https://private-user-images.githubusercontent.com/112397151/368872209-2a192688-bb2c-4af9-8a26-914c3bdff73f.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDIzOTUsIm5iZiI6MTcyNjc0MjA5NSwicGF0aCI6Ii8xMTIzOTcxNTEvMzY4ODcyMjA5LTJhMTkyNjg4LWJiMmMtNGFmOS04YTI2LTkxNGMzYmRmZjczZi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxMDM0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODdkYWFhN2E2ZDhkMzE1ODBkMTNkOTAxNjczZWZhN2RhMDBmZWEyZGRhOWQ4MmFlYzU5NWZlMmYyYTQ5MjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1mGAAfXRHmAcGRlrHZhwPof-wkhcM0ZKQtU7lmwOqaU)
> 
> 在dda的实验版上测试了，一样的结果。即使直接距离很近，但是不算作可接触。

这也太难了，建家的话，以往的版本只要是可视就可以读取，现在相当于半径也缩小了一圈，还不能建立东西，这有点不太人性化了，本事就很繁琐的工作

**Comment by WhiteCloud0123** [comment]
你不懂我的意思吗？
是你存在误解，本身就不存在“之前版本可以跨视觉无视其他条件搜寻物品。”

**Comment by WhiteCloud0123** [comment]
你没看我连dda实验版上都测试了吗，你还需要我去0.G给你测试吗？

**Comment by WhiteCloud0123** [comment]
谁知道你在之前存档是怎么理解的，人出现误解是很正常的，你那里一堆物品，没有知道你当时是怎么放的，让你得出的这个结论。

我没有修改过相关机制，之前的修改只影响npc的射击行为。

**Comment by WhiteCloud0123** [comment]
这已经是第二次出现花了一堆时间的无聊的求证了，我还要去给你验证它到底是一个特性还是一个bug，实际上我根本就没那么多时间，这更多只是我的一个兴趣，我又不欠你什么东西，平常还指导味那么重。真的是受够了。

**Comment by yxxwj** [comment]
> 这已经是第二次出现花了一堆时间的无聊的求证了，我还要去给你验证它到底是一个特性还是一个bug，实际上我根本就没那么多时间，这更多只是我的一个兴趣，我又不欠你什么东西，平常还指导味那么重。真的是受够了。

对不起，麻烦了，已经想到解决办法了，现在感觉这样的布局反而好看了一些
![Uploading Screenshot_20240919-191414_CDDA_Breeze.jpg…]()
