### ISSUE TITLE
自动进食/饮用区域的相关问题；放置的炮塔（monster）装填子弹的方式应该改善；区域清空时，遇到带有枪械模组的枪械时，移除一个枪械模组之后会中断清空行动

### ISSUE THREAD

**Issue by yxxwj** [WhiteCloud0123/CDDA-Breeze#821]
### 描述你遇到的bug

浩劫余生的各种炮塔安装的时候填装是直接填装子弹，但是被损毁或者开过几枪，这时候子弹掉落就会变成子弹带，虚空生产弹链，导致刷新大量弹链，，设置挖矿区域，O进行工作不享受自动进食，自动饮用

### 复现bug的步骤

无

### 截图

![Screenshot_20241007-160512_CDDA_Breeze](https://github.com/user-attachments/assets/be8adbb4-386f-4017-9ba7-0bfa89ec8d9c)

### 是否使用了第三方mod

否

### 游戏版本

9.8

### 系统

安卓

**Comment by yxxwj** [comment]
炮塔问题可以的话填装方式变成填装子弹带

**Comment by yxxwj** [comment]
还有一个Y区域清空物品的时候，到枪械就会停止，需要一次一次启动O进行

**Comment by yxxwj** [comment]
屠宰也不会自动进食

**Comment by WhiteCloud0123** [comment]
我很久之前看过这个地方，记得自动进食这一块有一个检查，而且这个检查在我看来并不是非常的合理。

可以先与dda尽可能在同等条件下进行对比测试。

同时，将来可能很长一段时间都不更新了，还是建议回归dda，等等0.H，起码能有一个社区支持。
