### ISSUE TITLE
NPC工作的相关问题

### ISSUE THREAD

**Issue by yxxwj** [WhiteCloud0123/CDDA-Breeze#860]
### 描述你遇到的bug

让NPC工作时条件不满足会生成大量的文本，造成游戏长时间卡顿，其次无法得知NPC是差什么，如果可以，建议添加得知NPC具体缺少什么，例如缺少技能或者什么工具

### 复现bug的步骤

无

### 是否使用了第三方mod

无

### 游戏版本

9.3

### 系统

Android

**Comment by WhiteCloud0123** [comment]
这个issue指的是npc工作，还是特指npc制作？
有什么可以很容易复现的步骤吗？

**Comment by yxxwj** [comment]
> 这个问题指的是全国人民代表大会/非玩家角色工作,还是特指全国人民代表大会/非玩家角色制作？ 有什么可以很容易复现的步骤吗？

非玩家角色工作，例如让NPC去建筑，规划好区域，对话让NPC去完成未完成建造，如果建筑配方缺失某样东西就会生成大量的在寻找工具文本，制作物品也是一样，把正在制作中的物品交给NPC去继续完成如果条件不满足了也是会这样

**Comment by WhiteCloud0123** [comment]
了解。
这段时间对npc制作有了很多兴趣，会先试着完成制作液体的功能。
