### ISSUE TITLE
放置怪物炮塔，装填弹药时出现了闪退

### ISSUE THREAD

**Issue by yxxwj** [WhiteCloud0123/CDDA-Breeze#872]
### 描述你遇到的bug

填装子弹袋闪退

### 复现bug的步骤

填装炮塔子弹

### 是否使用了非内置mod

否

### 游戏版本

9.9

### 系统

安卓

**Comment by WhiteCloud0123** [comment]
呃呃，这个地方在Windows和安卓平台出现了不一致的行为，在Windows上表现正常，但是安卓平台出现了闪退。

**Comment by yxxwj** [comment]
是的，刚刚测试过了，电脑上是正常的

**Comment by WhiteCloud0123** [comment]
只能找个时间实际地调试一下安卓程序了。😇

**Comment by WhiteCloud0123** [comment]
啊，是我最后不小心把迭代器的更新写错了😖。
